export const FETCH_BALANCE_BY_IBAN = 'pages/BalancePage/FETCH_BALANCE_BY_IBAN';
export const FETCH_BALANCE_BY_IBAN_SUCCESS = 'pages/BalancePage/FETCH_BALANCE_BY_IBAN_SUCCESS';
export const FETCH_BALANCE_BY_IBAN_FAILURE = 'pages/BalancePage/FETCH_BALANCE_BY_IBAN_FAILURE';
